version: "3.8"

services:
    db:
        image: mysql
        container_name: bd_simblog
        restart: always
        volumes:
            - db-data:/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin_simblog
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment :
            PMA_HOST: db
        networks:
            - dev

    mailer:
        image: schickling/mailcatcher
        ports: [1025, 1080]

    php8-sf6:
        container_name: php8-sf6
        build: php8-sf6
        volumes:
            - ./docker/vhosts:/etc/apache2/sites-enabled
        ports:
            - "8000:80"
        networks: 
            - dev
networks:
    dev:
volumes:
    db-data:

